# Generated by Django 4.1.7 on 2023-04-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GATA',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('studentName', models.CharField(max_length=100, unique=True)),
                ('hoursAvailable', models.PositiveSmallIntegerField(default=10)),
                ('officeHours', models.PositiveSmallIntegerField(default=1)),
                ('classTimes', models.CharField(default=None, max_length=255)),
                ('studentType', models.CharField(default='GA', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Semester', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('conflicts', models.PositiveSmallIntegerField(default=0)),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('labCode', models.PositiveSmallIntegerField(default=100)),
                ('labName', models.CharField(max_length=255)),
                ('labFaculty', models.CharField(max_length=255)),
                ('labSection', models.PositiveSmallIntegerField(default=1)),
                ('labMeetTimes', models.CharField(max_length=100)),
                ('activityTimes', models.CharField(max_length=255)),
                ('facultyTaught', models.BooleanField(default=True)),
                ('labPrepTime', models.PositiveSmallIntegerField(default=0)),
                ('GAPref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.AddField(
            model_name='gata',
            name='semYr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('courseCode', models.PositiveSmallIntegerField(default=100)),
                ('courseName', models.CharField(max_length=255)),
                ('courseSection', models.PositiveSmallIntegerField(default=1)),
                ('courseMeetTimes', models.CharField(max_length=100)),
                ('courseFaculty', models.CharField(max_length=255)),
                ('activityTimes', models.CharField(max_length=255)),
                ('GAPref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('MeetTimes', models.CharField(default=None, max_length=100)),
                ('GATAhrsused', models.FloatField(default=0.0)),
                ('GATAHrsRem', models.FloatField(default=0.0)),
                ('coursesAsn', models.CharField(max_length=255)),
                ('scheduleNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedules')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
                ('studentName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata', to_field='studentName')),
            ],
        ),
    ]
