# Generated by Django 4.1.1 on 2022-10-12 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('scheduleNum', models.IntegerField(primary_key=True, serialize=False)),
                ('coursesAsn', models.CharField(max_length=255)),
                ('hoursAsn', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GATA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('hoursAvailable', models.PositiveSmallIntegerField(default=10)),
                ('coursePref', models.CharField(max_length=255)),
                ('facultyPref', models.CharField(max_length=255)),
                ('officeHours', models.PositiveSmallIntegerField(default=1)),
                ('classTimes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Semester', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conflicts', models.PositiveSmallIntegerField(default=0)),
                ('scheduleNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.assignment')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('labCode', models.PositiveSmallIntegerField(default=100)),
                ('labName', models.CharField(max_length=255)),
                ('labFaculty', models.CharField(max_length=255)),
                ('labSection', models.PositiveSmallIntegerField(default=1)),
                ('labMeetTimes', models.CharField(max_length=100)),
                ('activityTimes', models.CharField(max_length=255)),
                ('GAPref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.AddField(
            model_name='gata',
            name='semYr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('courseCode', models.PositiveSmallIntegerField(default=100)),
                ('courseName', models.CharField(max_length=255)),
                ('courseSection', models.PositiveSmallIntegerField(default=1)),
                ('courseMeetTimes', models.CharField(max_length=100)),
                ('courseFaculty', models.CharField(max_length=255)),
                ('courseActivities', models.CharField(max_length=255)),
                ('activityTimes', models.CharField(max_length=255)),
                ('GAPref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata')),
                ('semYr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.gata'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='semYr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semesteryear'),
        ),
    ]
