# Generated by Django 4.1.3 on 2022-12-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='GATAid',
            new_name='studentName',
        ),
    ]
