# Generated by Django 4.1.1 on 2022-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_alter_assignment_schedulenum_alter_courses_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gata",
            name="studentType",
            field=models.CharField(default="GA", max_length=255),
        ),
    ]
