# Generated by Django 4.1.3 on 2022-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_courses_gapref_alter_labs_gapref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='GATAHrsRem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='GATAhrsused',
            field=models.FloatField(default=0.0),
        ),
    ]
