# Generated by Django 4.1.8 on 2023-05-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_courses_coursesection_alter_labs_labsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Conflict',
            field=models.BooleanField(default=False),
        ),
    ]
