# Generated by Django 4.1.1 on 2022-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_gata_studenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courseActivities',
        ),
        migrations.AddField(
            model_name='labs',
            name='facultyTaught',
            field=models.BooleanField(default=True),
        ),
    ]
