# Generated by Django 4.1.1 on 2022-11-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_courses_courseactivities_labs_facultytaught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gata',
            name='coursePref',
        ),
        migrations.RemoveField(
            model_name='gata',
            name='facultyPref',
        ),
    ]
