# Generated by Django 4.1.1 on 2022-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_gata_coursepref_remove_gata_facultypref'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='labPrepTime',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
